### ISSUE TITLE
Foundation Unity Example gives Package Manager Errors

### ISSUE THREAD

**Issue by andybak** [magnopus-opensource/connected-spaces-platform#108]
An error occurred while resolving packages:
  Project has invalid dependencies:
    connected-spaces-platform.unity.core: Request [GET https://npm.pkg.github.com/@magnopus-opensource/connected-spaces-platform.unity.core] failed because it lacks valid authentication credentials

**Comment by andybak** [comment]
I tried the npm install instructions just in case they were needed for the example project and got a similar error.

(It's odd to use npm directly with Unity - surely the Unity Package Manager should be the recommended way to install?)

**Comment by MAG-SamBirley** [comment]
Hey! Thanks for checking out CSP and reporting this. 🤗 
We've got the issue tracked now, and will be planning to address it in the near future - stay tuned!

**Comment by benmagnopus** [comment]
Andy, 
I appreciate you taking the time to let us know about this one.  
We'll get it in the queue quick!

-ben

**Comment by MAG-SamBirley** [comment]
Hey @andybak, in order to resolve your issue (and others!) we have moved CSP package hosting across to `npmjs`. 
There's some basic guidance [here](https://github.com/magnopus-opensource/connected-spaces-platform#-install) and some specific Unity {ackage Manager setup instructions here to [help](https://github.com/magnopus-opensource/connected-spaces-platform/wiki/Using-CSP-For-Unity).

Thank you again for reporting this, and let us know how you get on!
