### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by superwhyun** [magnopus-opensource/connected-spaces-platform#121]
**Describe the bug**

When I try to install the npm module, it says the following errors.

> npm install @magnopus-opensource/connected-spaces-platform.web
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@magnopus-opensource%2fconnected-spaces-platform.web - Not found
> npm ERR! 404 
> npm ERR! 404  '@magnopus-opensource/connected-spaces-platform.web@*' is not in this registry.
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

**To Reproduce**

npm install @magnopus-opensource/connected-spaces-platform.web

**Comment by MAG-SamBirley** [comment]
Hey! Thanks for much for checking us out.

Just wanted to to let you know that we've seen this, and are planning to relocated CSP web packages to npmjs in the next few weeks.

**Comment by MAG-SamBirley** [comment]
Hello! I'm happy to share that CSP packages are now hosted on `npmjs` rather than GitHub.

Please note that as part of this, we've dropped the `magnopus-opensource` scope on the pacakge. More info over [here](https://github.com/magnopus-opensource/connected-spaces-platform#-build-instructions).

Let us know how you get on!
