### ISSUE TITLE
Does/will Connected Spaces Platform support Unity WebGL?

### ISSUE THREAD

**Issue by ibytergj** [magnopus-opensource/connected-spaces-platform#273]
**Is your feature request related to a problem? Please describe.**

Hoping that CP will support Unity WebGL and or WebGPU builds in the future.

**Describe the solution you'd like**

Support for Unity WebGL and or WebGPU builds

**Describe alternatives you've considered**

N/A

**Comment by ibytergj** [comment]
I am just curious why you are choosing to not support WebGL/WebGPU with Unity if you want the widest adoption possible for CSP?

**Comment by MAG-SamBirley** [comment]
Totally fair question, thank you for asking!

Internally, we've got a lot of other features queuing up for next year, so when I said we have no near-term plans for Unity WebGL, it's because of internal work prioritisation rather than intent (or lack thereof).

However, whilst we're internally tied up on other features, we would very much welcome and support contributions towards enabling CSP on Unity WebGL. We believe CSP needs to be open source so that the entire OS community can mould it into the shape it needs to be, for all of us.

If you were inclined to do so, we would absolutely support efforts to add support for it in the meantime, and we'd be more than happy to give guidance/pointers along the way.
